import React from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const Terms = () => {
  return (
    <div className="bg-background flex flex-col overflow-x-hidden min-h-screen w-full">
      <Header />
      
      <main className="w-full flex flex-col items-center max-w-[1200px] mx-auto mt-[120px] md:mt-[180px] px-4 md:px-8 pb-20">
        <div className="w-full max-w-[900px] prose prose-slate dark:prose-invert max-w-none">
          {/* Title */}
          <h1 className="text-foreground text-[clamp(42px,5.5vw,68px)] font-medium leading-none tracking-tight mb-4">
            TERMS OF USE
          </h1>
          
          <p className="text-muted-foreground text-base md:text-lg mb-8">
            Kendall Square Technology and Services Private Limited
          </p>
          
          <p className="text-muted-foreground text-sm md:text-base mb-12">
            Last updated: February 2026
          </p>

          {/* Introduction */}
          <div className="mb-12 text-foreground text-base md:text-lg leading-relaxed">
            <p className="mb-4">
              This document constitutes an electronic record in terms of the Indian Contract Act 1872, the Information Technology Act 2000, and the rules, regulations and amendments made thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
            <p className="mb-4">
              The website domain name &lt;www.kiora.care&gt; and the associated mobile applications are owned by Kendall Square Technology and Services Private Limited. (CIN: U86905WB2025PTC282851), a company incorporated under the Companies Act, 2013, having its registered office at Ground Floor, 289, Shanti Pally, EKT, Kolkata -700107, West Bengal.
            </p>
            <p className="mb-4 font-semibold">
              THESE TERMS OF USE ("TERMS") GOVERN ACCESS TO AND USE OF THE PLATFORM (AS DEFINED BELOW) AVAILABLE BY THE COMPANY. YOU ARE REQUESTED TO CAREFULLY REVIEW THESE BEFORE ACCESSING OR USING THE PLATFORM OR AVAILING SERVICES USING THE PLATFORM.
            </p>
            <p className="mb-4">
              BY CLICKING "I AGREE", "SIGN UP", "PROCEED", OR ANY SIMILAR CONFIRMATION BUTTON, OR BY ACCESSING, BROWSING, REGISTERING ON, OR OTHERWISE USING THE PLATFORM (INCLUDING OUR WEBSITE, MOBILE APPLICATIONS, AND ANY RELATED DIGITAL SERVICES), YOU EXPRESSLY ACKNOWLEDGE THAT YOU HAVE READ AND CONSENT TO BE BOUND BY THESE TERMS OF USE. IF YOU DO NOT AGREE TO THESE TERMS, YOU MUST NOT ACCESS OR USE THE PLATFORM.
            </p>
            <p>
              In addition to these Terms, your use of any specific feature, service, functionality, or offering made available on the Platform including but not limited to appointment booking, teleconsultation, care plans, health tracking tools, automated insights, or any other related services shall be governed by any rules, guidelines, policies, operating procedures, service-specific terms, or additional documents applicable to such feature or service (collectively, the "Supplemental Terms"). All such Supplemental Terms are hereby incorporated into and form an integral part of these Terms by reference. In the event of any inconsistency, the Supplemental Terms applicable to a particular service shall prevail to the extent of such inconsistency.
            </p>
          </div>

          {/* Section 1 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              1. DEFINITIONS AND INTERPRETATION
            </h2>
            <div className="space-y-4 text-foreground text-base md:text-lg leading-relaxed">
              <p>
                <strong>1.1</strong> In these Terms, unless the context otherwise requires, the following words and expressions shall have the meanings set out below:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li><strong>a) "Applicable Laws"</strong> means all applicable laws, rules, regulations, directions, notifications, orders, and guidelines in force in India, including but not limited to the Information Technology Act, 2000, the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011, the Digital Personal Data Protection Act, 2023and any amendments thereto.</li>
                <li><strong>b) "Artificial Intelligence" or "AI"</strong> means algorithmic, machine-learning, or automated systems used to analyse, summarise, organise, or process data for assistive, informational, or operational purposes, and expressly excludes autonomous systems used for medical diagnosis, treatment decisions, or clinical prescriptions.</li>
                <li><strong>c) "Company", "Kiora", "we", "us", or "our"</strong> means Kendall Square Technology and Services Pvt. Ltd.</li>
                <li><strong>d) "Data Principal"</strong> means the individual to whom the Personal Data relates, as defined under the Digital Personal Data Protection Act, 2023.</li>
                <li><strong>e) "Information"</strong> means any data, content, materials, inputs, outputs, summaries, insights, recommendations, reports, messages, text, images, audio, video, health-related data, medical information, AI-generated content, educational materials, or other information that is: (i) provided by a User or on the User's behalf to the Company; (ii) generated, processed, or displayed through the Platform (including by AI-enabled tools); or (iii) made available through Third-Party Services, and includes both Personal Data and non-Personal Data, but excludes any binding medical advice, diagnosis, or treatment.</li>
                <li><strong>f) "Medical Emergency"</strong> means any acute or life-threatening medical condition requiring immediate in-person medical attention, including emergency hospitalisation or urgent clinical intervention.</li>
                <li><strong>g) "Prohibited Uses"</strong> means any use of the Platform that is unlawful, unauthorised, misleading, abusive, fraudulent, medically unsafe, or otherwise prohibited under these Terms or Applicable Laws.</li>
                <li><strong>h) "Personal Data"</strong> means any data relating to an identified or identifiable individual as defined under the Digital Personal Data Protection Act, 2023, and processed in accordance with the Privacy Policy.</li>
                <li><strong>i) "Platform"</strong> means the website located at www.kiora.care, the mobile application(s), and all related software, digital interfaces, systems, tools, and services owned or operated by Kiora, including updates and upgrades.</li>
                <li><strong>j) "Privacy Policy"</strong> means the privacy policy published by Kiora on the Platform, as amended from time to time, which forms an integral part of these Terms.</li>
                <li><strong>k) "Sensitive Personal Data"</strong> means sensitive personal data or information as defined under the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011, including health and medical information.</li>
                <li><strong>l) "Services"</strong> means the digital health care support services offered through the Platform, including health monitoring, health data tracking, appointment booking, teleconsultation facilitation, nutrition plans, home-visit support, educational content, AI-assisted summaries.</li>
                <li><strong>m) "Subscription"</strong> means any paid plan or subscription package purchased by a User to access specific features or Services on the Platform, as described in Clause 13.</li>
                <li><strong>n) "Supplemental Terms"</strong> means any service-specific terms, guidelines, policies, operating procedures, or additional documents applicable to a particular feature or Service, which are incorporated into these Terms by reference.</li>
                <li><strong>o) "Teleconsultation"</strong> means a remote consultation conducted through electronic communication tools, which may be facilitated by the Platform solely as a technology intermediary, without the Company providing or practicing telemedicine.</li>
                <li><strong>p) "Third-Party Services"</strong> means any websites, services, software, integrations, payment processors, or resources provided by third parties and made available through or linked to the Platform.</li>
                <li><strong>q) "User" or "You"</strong> means any individual who accesses, browses, registers on, or uses the Platform, including a parent or legal guardian when acting on behalf of a minor, where permitted under these Terms.</li>
              </ul>
              <p>
                <strong>1.2 Interpretation.</strong><br />
                Unless the context otherwise requires: (a) words importing the singular include the plural and vice versa; (b) headings are for convenience only and shall not affect interpretation; (c) the words "include", "includes", and "including" shall be construed as being followed by "without limitation"; (d) references to "Clauses" refer to clauses of these Terms; (e) any reference to a statute or law includes amendments, replacements, and re-enactments.
              </p>
            </div>
          </section>

          {/* Section 2 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              2. CHANGES TO TERMS
            </h2>
            <div className="space-y-4 text-foreground text-base md:text-lg leading-relaxed">
              <p>
                <strong>2.1</strong> We reserve the right to modify, update, or revise these Terms from time to time. Any such changes shall become effective upon being posted on the Platform, unless a later effective date is expressly stated.
              </p>
              <p>
                <strong>2.2.</strong> Where required by Applicable Law, we will provide reasonable notice of material changes to these Terms. Your continued access to or use of the Platform after the effective date of any changes shall constitute your acceptance of the revised Terms. If you do not agree to the modified Terms, you must discontinue use of the Platform, and certain features or Services may be limited or unavailable to you.
              </p>
              <p>
                <strong>2.3</strong> You are encouraged to review these Terms periodically to remain informed of any updates. The most current version of the Terms, as made available on the Platform, shall supersede all prior versions.
              </p>
              <p>
                <strong>2.4</strong> Any changes that result in the collection, use, or processing of additional Personal Data shall be governed by our Privacy Policy.
              </p>
            </div>
          </section>

          {/* Section 3 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              3. CHANGES TO WEBSITE AND SERVICES
            </h2>
            <p className="text-foreground text-base md:text-lg leading-relaxed">
              <strong>3.1.</strong> Kiora may, at its sole discretion, update, modify, enhance, suspend, or discontinue any feature, functionality, interface, content, or component of the Platform at any time for purposes including, but not limited to, system maintenance, security enhancement, regulatory or legal compliance, performance improvement, correction of errors, or user-experience optimisation.
            </p>
          </section>

          {/* Section 4 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              4. ELIGIBILITY
            </h2>
            <div className="space-y-4 text-foreground text-base md:text-lg leading-relaxed">
              <p>
                <strong>4.1.</strong> Use of the Platform is permitted only to individuals who are 18 (eighteen) years of age or older and are competent to enter a legally binding contract.
              </p>
              <p>
                <strong>4.2.</strong> In case a User is under 18 years of age, the User may access or use the Platform solely with the informed consent, active supervision, and involvement of their parent or legal guardian, who must accept these Terms on such User's behalf including taking responsibility for your actions and compliance with these Terms.
              </p>
              <p>
                <strong>4.3.</strong> In the case of minors, any processing of Personal Data-including health information shall be carried out as per Kiora's Privacy Policy.
              </p>
              <p>
                <strong>4.4.</strong> Kiora reserves the right to refuse, restrict, or terminate access of any person to the Platform at its sole discretion including if it has reason to believe that a User does not meet the above eligibility requirements or where required to comply with Applicable Laws.
              </p>
            </div>
          </section>

          {/* Section 5 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              5. ACCOUNT REGISTRATION AND SECURITY
            </h2>
            <div className="space-y-4 text-foreground text-base md:text-lg leading-relaxed">
              <p>
                <strong>5.1</strong> To access and use the Platform, you will be required to create a User account by completing the registration process, following which it will be deemed that you have read, understood and accepted the Terms. By registering, you acknowledge that your account and any information associated with it will be used strictly in accordance with these Terms and Kiora's Privacy Policy.
              </p>
              <p>
                <strong>5.2</strong> During registration and throughout your use of the Platform, you may be required to provide some or all of the Information (including Personal Data and Sensitive Personal Data). You understand and acknowledge that providing such Information is required for you to avail the Services and agree that: (a) the Information provided by you is voluntary, true, accurate, current, and complete at the time of submission and is not coerced; (b) you shall keep your Information updated to ensure its continued accuracy, particularly health-related Information that may be relied upon by the Company and its representatives in connection with the Services; and (c) Information may be collected, used, stored, and processed by Kiora in accordance with the Privacy Policy, Applicable Laws, and, where relevant, parental or guardian consent requirements. You acknowledge that providing incorrect, incomplete, or misleading Information may adversely affect clinical outcomes or teleconsultation quality, and Kiora shall not be responsible or liable for any consequences resulting due to provision of inaccurate, incorrect, incomplete, or misleading Information.
              </p>
              <p>
                <strong>5.3</strong> You are responsible for maintaining the confidentiality and security of your account credentials, including your username, password, registered devices, and access tokens. You agree not to share your account or login credentials with any other person, except as expressly permitted under these Terms.
              </p>
              <p>
                <strong>5.4</strong> You shall be solely responsible for all activities that occur in your User account, whether or not expressly authorised by you. Kiora disclaims any liability for losses arising from unauthorised access to your account resulting from your failure to maintain adequate security of your credentials, device, or access controls.
              </p>
              <p>
                <strong>5.5</strong> If you access, browse, or use the Platform on behalf of another individual (including a minor or dependent), you represent and warrant that you have the legal authority to bind such individual to these Terms. In the event such individual disputes or refuses to be bound by these Terms, you agree not to access the Platform or use the Services and be responsible for, and indemnify Kiora for any loss, claims, or liability arising from such access or use.
              </p>
              <p>
                <strong>5.6</strong> If you believe, or have reason to believe, that the security of your account has been compromised, or that any unauthorised activity has occurred in relation to your account or the Information associated with it, you shall immediately notify Kiora using the contact details provided on the Platform.
              </p>
              <p>
                <strong>5.7</strong> Upon detection of any actual or suspected security breach, unauthorised access, or illegal use of the Platform or Information, Kiora may, without prior notice and without liability, require you to change your credentials, suspend or terminate your account (temporarily or permanently), or take any other measures reasonably necessary at its discretion to protect Users, Information, Personal Data, and the integrity of the Platform.
              </p>
              <p>
                <strong>5.8</strong> You shall not use the Platform or any Information for any illegal, unlawful, unauthorised, or Prohibited Use, including but not limited to: (a) impersonation or unauthorized access to accounts or systems; (b) submission, upload, or dissemination of false, misleading, incomplete, or harmful medical, biological, or health-related Information; (c) infringement of intellectual property rights; (d) interference with, disruption of, or compromise to the Platform's security, systems, teleconsultation features, AI tools, or health-data infrastructure; or (e) any activity that violates Applicable Laws.
              </p>
              <p>
                <strong>5.9</strong> In the event of any Prohibited Use, Kiora reserves the right to suspend or terminate your account immediately and without notice, restrict future access to the Platform, and report such conduct to relevant authorities as it deems fit or required under Applicable Laws.
              </p>
            </div>
          </section>

          {/* Section 6 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              6. NATURE OF SERVICES PROVIDED
            </h2>
            <div className="space-y-4 text-foreground text-base md:text-lg leading-relaxed">
              <p className="font-semibold">
                6.1 THE PLATFORM IS A DIGITAL HEALTH CARE SUPPORT PROGRAM DESIGNED TO PROVIDE INFORMATIONAL AND COORDINATION SERVICES. USE OF THE PLATFORM DOES NOT CREATE A DOCTOR–PATIENT RELATIONSHIP BETWEEN THE USER AND THE COMPANY. THE COMPANY DOES NOT PRACTISE MEDICINE AND DOES NOT PROVIDE MEDICAL ADVICE, DIAGNOSIS, PRESCRIPTIONS, OR TREATMENT, INCLUDING TELEMEDICINE SERVICES.
              </p>
              <p>
                <strong>6.2</strong> The Platform is intended for informational and support purposes only and is not a substitute for physical medical and doctor consultations, personalised clinical evaluation, diagnosis, treatment, or emergency care. In the event of any Medical Emergency, the User shall seek immediate in-person medical attention from his own independent medical practitioner, doctor, without placing any reliance on the Platform.
              </p>
              <p>
                <strong>6.3.</strong> The Platform may enable Users to manually enter, store, and track clinical parameters and renal-related health data, and may also provide general educational content such as articles, videos, guides, diet charts, or care-related materials. All such tools and content are general in nature, provided for self-management and informational purposes only, and must not be relied upon as personalised medical advice or clinical evaluation.
              </p>
              <p>
                <strong>6.4.</strong> Medical Device Disclaimer. The Platform (including any content, tools, AI-assisted features, and summaries) is intended to support renal-care coordination, self-management, and informational purposes only, and is not intended to be used as, nor is it marketed or represented as, a medical device or Medical Device Software / Software as a Medical Device for diagnosis, treatment decisions, prognosis, or prescription.
              </p>
            </div>
          </section>

          {/* Section 7 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              7. USER'S MEDICAL INFORMATION
            </h2>
            <div className="space-y-4 text-foreground text-base md:text-lg leading-relaxed">
              <p>
                <strong>7.1.</strong> The User is solely responsible for ensuring that all Information submitted on the Platform is accurate, complete, and up to date. The User shall promptly update such Information whenever there is any change or if requested during a consultation.
              </p>
              <p>
                <strong>7.2.</strong> All Information uploaded by the User is processed by the Platform 'as-is', without any independent verification, validation, or clinical interpretation by Kiora. The User acknowledges that incomplete, inaccurate, outdated, or misleading Information may adversely affect any insights, reminders, recommendations, or teleconsultation outcomes provided through the Platform.
              </p>
              <p>
                <strong>7.3.</strong> Kiora shall not be liable for any error, omission, adverse event, misinterpretation, delay, or medical consequence arising directly or indirectly from any Information provided by the User or by any representative authorised to provide Information on their behalf, the nature of which may be incorrect, incomplete, outdated, or misleading.
              </p>
              <p>
                <strong>7.4.</strong> The User expressly agrees that the accuracy of their Information is critical and that Kiora cannot be held responsible for any outcome resulting from User data.
              </p>
            </div>
          </section>

          {/* Section 8 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              8. USE OF ARTIFICIAL INTELLIGENCE
            </h2>
            <div className="space-y-4 text-foreground text-base md:text-lg leading-relaxed">
              <p>
                <strong>8.1</strong> Kiora may utilise AI and machine-learning technologies, including those provided by third-party service providers, for the purposes of processing Personal Data in connection with the delivery, operation, and improvement of the Services. Kiora does not deploy autonomous or decision-making AI systems for clinical diagnosis or treatment and does not operate proprietary in-house AI models.
              </p>
              <p>
                <strong>8.2</strong> AI-enabled tools may be used for limited and assistive functions, including pattern recognition, trend analysis, summary of User-entered information, risk flagging, automated reminders, and generation of analytical insights, strictly as support tools. Any such outputs are informational in nature and do not constitute medical advice, diagnosis, or clinical decision-making. The User agrees that AI-assisted outputs that relate to health or medical information require independent review by qualified medical practitioners including nephrologists and other specialists and is not included as part of the services. The User shall seek guidance, advice and validation for all such ai-assisted outputs, from his or her independent medical practitioner, before using the AI-assisted outputs in any way.
              </p>
              <p>
                <strong>8.3</strong> Where AI systems are used to process Personal Data, such processing shall be carried out only with the Data Principal's valid consent and in accordance with this Privacy Policy and Applicable Laws.
              </p>
              <p>
                <strong>8.4</strong> Kiora may use anonymised and aggregated data, from which individuals cannot be identified, to train, evaluate, or improve AI systems, conduct analytics, or enhance service quality, to the extent permitted under Applicable Laws. Such anonymised or aggregated data shall not be used to re-identify any individual.
              </p>
              <p>
                <strong>8.5</strong> Kiora ensures that any third-party AI service providers engaged by it are subject to contractual obligations requiring compliance with Applicable Laws, confidentiality requirements, and appropriate technical and organisational safeguards for the protection of Personal Data.
              </p>
            </div>
          </section>

          {/* Section 9 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              9. INTELLECTUAL PROPERTY RIGHTS
            </h2>
            <div className="space-y-4 text-foreground text-base md:text-lg leading-relaxed">
              <p>
                <strong>9.1.</strong> All material and content on the Platform, including images, illustrations, text, graphics, logos, button icons, audio clips, digital downloads, data compilations and software, is our property, or the property of our affiliates or content suppliers, and is protected by Indian and international intellectual property law, including copyright, authors' rights, database rights laws and trademarks.
              </p>
              <p>
                <strong>9.2.</strong> You hereby agree not to copy, reproduce, republish, upload, post, transmit or distribute such material in any way, including by e-mail or other electronic means, whether directly or indirectly, and you must not assist any other person to do so. Without the prior written consent of the owner, modification of the materials, use of the materials on any other website or use of the materials for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks and other proprietary rights, and is prohibited.
              </p>
            </div>
          </section>

          {/* Section 10 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              10. LICENSE TO USE WEBSITE AND MOBILE APPLICATIONS
            </h2>
            <p className="text-foreground text-base md:text-lg leading-relaxed">
              <strong>10.1.</strong> We grant you a limited, revocable, non-exclusive, non-transferable license to access and make personal use of the Platform, but not to modify it, or any portion of it, except with our written consent. This license does not include any resale or commercial use of the Platform, or its contents; any derivative use of the Platform, or its contents; any downloading or copying of account information for the benefit of another user, or any use of data mining, robots or similar data gathering and extraction tools.
            </p>
          </section>

          {/* Section 11 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              11. MOBILE APPLICATIONS
            </h2>
            <div className="space-y-4 text-foreground text-base md:text-lg leading-relaxed">
              <p>
                <strong>11.1.</strong> If you download our mobile application from a third-party app store or platform such as Apple App Store or Google Play Store, you agree to comply with the respective platform's Terms of Service.
              </p>
              <p>
                <strong>11.2.</strong> We may automatically update the mobile application on your device when a new version is available. Your continued use of the mobile application after such update constitutes your acceptance of the revised application.
              </p>
              <p>
                <strong>11.3.</strong> Our mobile application may request specific permissions on your device, such as camera access, location Services, or push notifications. You can manage these permissions through your device settings. Please note that certain features of the application may not function properly if specific permissions are denied.
              </p>
            </div>
          </section>

          {/* Section 12 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              12. THIRD-PARTY SERVICES AND LINKS
            </h2>
            <div className="space-y-4 text-foreground text-base md:text-lg leading-relaxed">
              <p className="font-semibold">
                12.1 THE COMPANY DOES NOT PROVIDE ANY MEDICAL ADVICE OR DIAGNOSIS OR CLINICAL SERVICES THROUGH THE PLATFORM, AND IS NOT RESPONSIBLE FOR ANY INTERACTIONS, CONSULTATIONS OR TRANSACTIONS BETWEEN YOU AND ANY MEDICAL PRACTITIONERS OR THIRD-PARTY VENDORS.
              </p>
              <p>
                <strong>12.2</strong> The Platform operates solely as a technology facilitator that enables you to identify, connect with vendors and avail services offered by third-party vendors, including laboratory testing and related services.
              </p>
              <p>
                <strong>12.3</strong> Vendors listed on the platform have represented to the Company that they are duly qualified and/or hold the requisite licenses and approvals, as applicable, to provide their services in India. The Company will not undertake an independent diligence to verify such representations, and it does not guarantee their accuracy. The Company and its officers, representatives or personnel shall not be liable for any misrepresentation, omission, negligence or misconduct on the part of the vendor. Further, the Company does not recommend or endorse any representations or warranties, express or implied, regarding the quality, safety, accuracy, suitability, or outcomes of any services provided by third-party vendors.
              </p>
              <p>
                <strong>12.4</strong> The Platform may integrate with or contain links to third-party websites, services, or resources that are not owned or controlled by us. We are not responsible for the content, privacy policies, or practices of any third-party websites or services.
              </p>
              <p>
                <strong>12.5</strong> The presence of any third-party link, integration, or feature on the Platform shall not be construed as an endorsement, recommendation, or guarantee by Kiora. Access to or use of Third-Party Services is at the User's sole discretion and risk and is governed exclusively by the terms and policies of the respective third party.
              </p>
              <p>
                <strong>12.6</strong> Payment for the Services may be processed through the third-party internet payment service providers. By purchasing any Services through the Platform, You hereby consent and agree to abide by such third-party internet payment service providers' applicable terms and conditions and privacy policies. You agree and acknowledge that Kiora has no responsibility or liability under the terms and conditions and policies of the third-party internet payment service provider. In the event such third-party internet payment service providers' customer terms and conditions or privacy policies are not acceptable to you, please do not purchase the Services through such third-party internet payment service providers.
              </p>
              <p>
                <strong>12.7</strong> Any teleconsultation accessed through the Platform is provided solely by practitioners in their personal professional capacity. The Company does not control or influence clinical judgment by the User's doctors or medical practitioners and is not responsible for compliance with laws or professional guidelines applicable to such practitioners.
              </p>
            </div>
          </section>

          {/* Section 13 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              13. TERMS OF PAYMENTS
            </h2>
            <div className="space-y-4 text-foreground text-base md:text-lg leading-relaxed">
              <p>
                <strong>13.1.</strong> Access to certain features of the Platform, including care plans, teleconsultations, or other premium Services, may require the User to purchase a monthly, quarterly, or annual Subscription. You agree to pay to us fees for the Services you wish to avail. All fees shall be displayed at the time of purchase and are payable in advance.
              </p>
              <p>
                <strong>13.2.</strong> All prices are listed in Indian Rupees (INR) unless stated otherwise. Applicable taxes, including GST, may be charged in addition to the Subscription fee. Kiora reserves the right to revise pricing at any time, and any change will be communicated to the User in accordance with the Terms.
              </p>
              <p>
                <strong>13.3.</strong> Unless expressly stated otherwise, all Subscription fees are non-refundable, including in cases of partial use, non-use, cancellation before the end of the billing cycle, or dissatisfaction with the Services.
              </p>
              <p>
                <strong>13.4</strong> Payments may be facilitated through independent third-party payment processors, the provisions for which shall be governed by clause 12 of these Terms.
              </p>
              <p>
                <strong>13.5.</strong> Where enabled, Subscriptions may automatically renew at the end of each billing cycle at the then-current price, unless the User disables auto-renewal prior to renewal. By enabling auto-renewal, the User authorises Kiora or its payment processor to automatically charge the applicable fee.
              </p>
              <p>
                <strong>13.6.</strong> If a payment is declined, reversed, or otherwise fails, Kiora may suspend or restrict access to paid features until the outstanding amount is successfully collected. Repeated failures may result in cancellation of the Subscription.
              </p>
              <p>
                <strong>13.7.</strong> Kiora may generate electronic invoices or payment confirmations for Subscription charges, which shall be provided to the User via email or within the Platform.
              </p>
            </div>
          </section>

          {/* Section 14 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              14. DISCLAIMER OF WARRANTIES
            </h2>
            <div className="space-y-4 text-foreground text-base md:text-lg leading-relaxed">
              <p>
                <strong>14.1.</strong> The Platform, its features, and all content made available through it-including health insights, teleconsultation functionality, AI-generated summaries, graphics, educational material, and any third-party content, are provided on an "as is", "as available", and "with all faults" basis. Kiora makes no warranties or representations, express or implied, regarding the accuracy, completeness, timeliness, reliability, suitability, availability, uninterrupted operation, or error-free performance of the Platform or any content displayed on it.
              </p>
              <p>
                <strong>14.2.</strong> Kiora does not warrant that: (a) The Platform will meet the User's expectations or health outcomes. (b) Any medical or health-related insights, summaries, AI outputs, or reminders will be clinically accurate, validated, or fit for diagnostic or therapeutic use; (c) Teleconsultations or advice if provided will achieve any particular result; (d) The Platform will be free from malware, viruses, or harmful components; or (e) Data transmission over the Internet will be secure, uninterrupted, or free from loss, corruption, or delays.
              </p>
              <p>
                <strong>14.3.</strong> No information, recommendation, or AI-generated insight on the Platform shall constitute a medical warranty, diagnosis, or assurance of outcome.
              </p>
              <p>
                <strong>14.4</strong> Any medical advisory members, clinical experts, or panel of doctors displayed or referenced on the Platform are engaged solely in an independent capacity and, where applicable, provide non-binding guidance to the Platform. The presence, listing, or association of any such medical practitioner on the Platform does not create a doctor–patient relationship between the Platform (or the Company) and any User, nor does it constitute the provision of medical advice, diagnosis, or treatment by the Company. If a User chooses to consult, engage, or interact with a doctor or registered medical practitioner through or in connection with the Platform, such engagement is undertaken voluntarily and at the User's sole discretion. Any medical advice, opinion, prescription, or treatment provided is rendered exclusively by the respective medical practitioner in their independent professional capacity, and the Company shall not be responsible or liable for the content, accuracy, or outcomes of such advice or services.
              </p>
            </div>
          </section>

          {/* Section 15 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              15. LIMITATION OF LIABILITY
            </h2>
            <div className="space-y-4 text-foreground text-base md:text-lg leading-relaxed">
              <p>
                <strong>15.1</strong> To the maximum extent permitted under applicable law, Kiora, its directors, employees, personnel, contractors, advisory board members and third-party service providers shall not be liable for any direct, indirect, incidental, special, consequential, punitive, exemplary, or economic losses, including loss of data, revenue, business opportunities, personal injury, medical complications, or health outcomes, arising out of or in connection with the User's access to, use of, or inability to use the Platform or Services, reliance on any user-provided, third-party, AI-generated, or automated information or insights, teleconsultations or interactions, Third-Party Services or integrations, technical failures or service interruptions, or any data loss, unauthorised access, or security incident, notwithstanding the implementation of reasonable security practices in accordance with applicable law.
              </p>
              <p>
                <strong>15.2.</strong> In no event shall the total aggregate liability of Kiora for any claims arising out of or related to the Platform, whether in contract, tort, negligence, strict liability, or otherwise, exceed the total Subscription fees actually paid by the User to Kiora in the three (3) months immediately preceding the event giving rise to the claim.
              </p>
              <p>
                <strong>15.3.</strong> Nothing in this clause shall exclude or limit liability where such exclusion or limitation is prohibited under applicable Indian law.
              </p>
            </div>
          </section>

          {/* Section 16 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              16. INDEMNIFICATION
            </h2>
            <p className="text-foreground text-base md:text-lg leading-relaxed">
              You agree to defend, indemnify and hold Kiora and its affiliates, contractors, employees, officers, directors, advisory members, agents and third party partners harmless from and against any and all claims, losses, damages, liabilities, costs and expenses (including without limitation, reasonable legal fees and expenses), caused by or arising due to (a) your access to or use or misuse of the Platform or any Services, (b) any breach or violation of any of the Terms of Use or by covenants made by you to the Platform, (c) any infringement or alleged infringement by User or by any other person of the User's account, including of any intellectual property or other right of any person, (d) any breach of any Applicable Laws, or (e) any fraudulent, false, misleading inaccurate, or incomplete information, content or feedback provided by you, including any feedback or conduct that may adversely affect Kiora's business and reputation or its Users.
            </p>
          </section>

          {/* Section 17 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              17. TERM AND TERMINATION
            </h2>
            <div className="space-y-4 text-foreground text-base md:text-lg leading-relaxed">
              <p>
                <strong>17.1.</strong> These Terms remain valid, binding, and enforceable for as long as the User continues to access or use the Platform, having a perpetual and continuing effect unless and until terminated either: (a) by the User, by discontinuing all use of the Services; or (b) by Kiora, in accordance with the provisions set out hereunder.
              </p>
              <p>
                <strong>17.2.</strong> Kiora may, at its sole and absolute discretion, suspend or terminate the User's account or access to the Platform or Services at any time, with or without cause or prior notice, where the User breaches these Terms, where any information provided by the User cannot be verified, or where the User's conduct or continued access is reasonably believed to be unlawful, fraudulent, abusive, infringing, or otherwise harmful, or may expose Kiora, the Platform, other users, or third parties to legal, financial, reputational, operational, or security risks, or where such action is necessary to protect the integrity, security, or functioning of the Platform or to comply with applicable laws or regulatory requirements.
              </p>
              <p>
                <strong>17.3.</strong> Upon termination for any reason of the Terms by either You or Us, you must promptly destroy all materials downloaded or otherwise obtained from the Platform, as well as all copies of such materials, whether made under the Terms of Use or otherwise. Any such termination of these Terms shall not cancel your obligation to pay for the product already ordered from the Website or affect any liability that may have arisen under these Terms.
              </p>
            </div>
          </section>

          {/* Section 18 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              18. PRIVACY AND COOKIES
            </h2>
            <div className="space-y-4 text-foreground text-base md:text-lg leading-relaxed">
              <p>
                <strong>18.1.</strong> The collection, use, storage, retention, disclosure, and processing of any Personal Data or Sensitive Personal Data provided by the User through the Platform shall be governed by Kiora's Privacy Policy, which forms an integral part of these Terms of Use. The Privacy Policy shall be read in conjunction with and forms an inseparable part of these Terms.
              </p>
              <p>
                <strong>18.2.</strong> By continuing to use the Platform, the User expressly acknowledges and agrees to the collection and processing of their Personal Data in accordance with the practices described in the Privacy Policy.
              </p>
            </div>
          </section>

          {/* Section 19 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              19. DISPUTE RESOLUTION
            </h2>
            <div className="space-y-4 text-foreground text-base md:text-lg leading-relaxed">
              <p>
                <strong>19.1</strong> In the event of any controversy, dispute, claim, or difference arising out of, in connection with, or relating to this Term of Use, including its breach, termination, or validity ("Dispute"), the parties shall first attempt to resolve the Dispute amicably through good faith negotiations. Such negotiations shall commence immediately upon one party delivering a written notice of Dispute to the other party.
              </p>
              <p>
                <strong>19.2.</strong> If the Dispute cannot be resolved through good faith negotiations within ninety (90) days from the date of the written notice, either party may initiate legal proceedings. The parties hereby irrevocably agree that the courts located within Kolkata, West Bengal shall have exclusive jurisdiction to hear, settle, and/or determine any Dispute arising out of or in connection with this Term of Use.
              </p>
              <p>
                <strong>19.3.</strong> These Terms, and any non-contractual obligations arising out of or in connection with it, shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law principles.
              </p>
              <p>
                <strong>19.4.</strong> To the extent permitted by applicable law, any cause of action or claim, You may have arising out of or relating to this Term of Use or the Services must be commenced within three months after the cause of action accrues; otherwise, such cause of action or claim is permanently barred.
              </p>
            </div>
          </section>

          {/* Section 20 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              20. GENERAL PROVISIONS
            </h2>
            <div className="space-y-4 text-foreground text-base md:text-lg leading-relaxed">
              <p>
                <strong>20.1. Entire Agreement.</strong> These Terms, together with the Privacy Policy and any other policies referenced herein, constitute the entire Terms of Use between you and Us regarding the Platform.
              </p>
              <p>
                <strong>20.2. Severability.</strong> If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall remain in full force and effect.
              </p>
              <p>
                <strong>20.3. No Waiver.</strong> Our failure to enforce any right or provision of these Terms will not be considered a waiver of such right or provision.
              </p>
              <p>
                <strong>20.4. Electronic Communications.</strong> When you use our Services or send emails to us, you are communicating with us electronically. You consent to receive communications from us electronically. We will communicate with you by email or by posting notices on the Website, or through the mobile applications. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.
              </p>
            </div>
          </section>

          {/* Section 21 */}
          <section className="mb-10">
            <h2 className="text-foreground text-[clamp(28px,4vw,36px)] font-semibold mb-6">
              21. GRIEVANCE REDRESSAL
            </h2>
            <p className="text-foreground text-base md:text-lg leading-relaxed">
              For any grievances, complaints, or concerns relating to the Platform or its Services, Users may write to <a href="mailto:care@kiora.care" className="text-primary hover:underline">care@kiora.care</a>
            </p>
          </section>
        </div>
      </main>

      <div className="w-full px-4 md:px-4 lg:px-6 max-w-full overflow-x-hidden">
        <Footer />
      </div>
    </div>
  );
};

export default Terms;
